negative = "<!:source_pony, source_furry, source_cartoon, score_6, score_5, score_4, worst quality, low quality, normal quality>"

[base]
_t="score_9, score_8_up, score_7_up, source_anime, rating_safe"

[base.quality]
_t="best quality, masterpiece"

[girl]
_t="""1girl, perfect anatomy, 
(detailed skin), (detailed face), (beautiful detailed eyes),  
shiny hair, 
"""

makeup = "makeup, juwelry, piercings, ring, nail polish, hair ornament"

[girl.hair]
_t="wavy midium bob hair"
black = "black hair"
silver = "silver hair"
blonde = "blonde hair"
pink = "pink hair"
blue = "blue hair"
brown = "brown hair"
orange = "orange hair"

[pose.photo]
_t="looking at viewer, cowboy shot, ${action}"
[pose.photo._v]
action=[
    "dancing",
    "paw pose",
    "claw pose",
    "selfie",
    "hugging a stuffed toy",
    "sitting",
    "crossed legs",
    "girly running",
    "fighting stance",
]

[where]
_t="detailed background"

[where.indoor]
_t="detailed background, indoor"
jp_room = "Japanese-style room"
office = "office, room, desk"
classroom = "classroom, desk, wooden floor"

["<lora>"]
"dir_name\\lora_name.safetensors" = "lora default prompt"
